title: 'اهلا وسهلا '
description: "محفضة شخصية \U0001F5A4"
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /omar502io
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
theme: jekyll-theme-leap-day
